### ISSUE TITLE
홈페이지 타이틀

### ISSUE THREAD

**Issue by jinhyukoo** [Zigje9/Z9#12]
제구님 안녕하세요! 포트폴리오 사이트 잘 봤습니다! 날이 갈수록 성장하시는 모습이 멋있고 동기부여가 되네요!

별 건 아니고 홈페이지 타이틀이 React App 으로 되어 있던데 이 부분 수정하면 좀 더 완성도가 높아질 것 같아요!

얼른 모두 좋은 소식 들고 다시 만나기를 기대합니다!

**Comment by Zigje9** [comment]
반갑습니다 진혁님 :) 타이틀 미처 신경쓰지 못했네요 수정할게요~ 좋은 지적 감사합니다! 
조만간 만나요~ !!
